### PR TITLE
issue 12: update comment

### PR DESCRIPTION
**Pull request by ashishgoyal21**

### CODE REVIEW

**Comment by iit2009060** [comment]
@ashishgoyal21   It was assigned to me .And i already send the PR . How could you assign someone else issue to yourself.

**Comment by ashishgoyal21** [comment]
I think multiple people can work on the same issue. I didn't see a PR when I started working on the issue.

**Comment by iit2009060** [comment]
I already sent  a PR. And I dont think it is the case as you mentioned.  Otherwise it will lead to lots of conflicts.

**Comment by jeffdonthemic** [comment]
@ashishgoyal21, sorry for the confusion here. I'm am going to pay you as well for this issue.

**Pull request closed without merging**
